@startuml

title Диаграмма сущностей

entity Пользователь {
    * id Уникальный идентификатор
    * name Имя пользователя
    * avatar URL для картинки пользователя
}

entity Дом {
    * id Уникальный идентификатор
    * name Название дома
    * user_id Идентификатор владельца
    * avatar URL для картинки ljvf
}

entity Устройство {
    * id Уникальный идентификатор
    * type_id Тип устройства
    * serial Серийный номер
    * control_url Адрес для управления
    * control_creds Данные авторизации
    * home_id идентификатор дома
}

entity "Тип устройства" {
    * id Уникальный идентификатор типа
    * name Название
    * avatar URL для картинки устройства
}

entity "Данные устройства" {
    * id Уникальный идентификатор записи
    * device_id Идентификатор устройства
    * value_name Имя параметра
    * value Значение параметра
    * updated_at Дата последнего обновления
}


Дом }o--|| Пользователь
Устройство }o--|| Дом
Устройство ||--|| "Тип устройства"
"Данные устройства" }o--|| Устройство

@enduml