@startuml

title Запись данных сенсоров

Датчик -> "Api Gateway"
"Api Gateway" -> "Приемник данных"
"Приемник данных" -> Kafka

Kafka -> "Обработчик данных температуры"
Kafka -> "Обработчик данных света"
Kafka -> "Обработчик данных запорных устройств"

"Обработчик данных температуры" -> "БД данных сенсоров"
"Обработчик данных света" -> "БД данных сенсоров"
"Обработчик данных температуры" -> "БД данных сенсоров"

@enduml