/*
 * Устройства
 *
 * Описание синхронного API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Команда
type Command struct {
	// Имя команды
	Name string `json:"name,omitempty"`
	// Аргументы
	Args string `json:"args,omitempty"`
}

const (
	PowerCmdName = "power"
	PowerOn      = "on"
	PowerOff     = "off"
)

var (
	TurnOn = Command{
		Name: PowerCmdName,
		Args: PowerOn,
	}

	TurnOdd = Command{
		Name: PowerCmdName,
		Args: PowerOff,
	}
)
