/*
 * Устройства
 *
 * Описание синхронного API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Устройство
type Device struct {
	// Уникальный идентификатор
	Id int32 `json:"id,omitempty"`
	// Серийный номер устройства
	Serial string `json:"serial,omitempty"`
	// Тип устройства
	Type_ string `json:"type,omitempty"`
	// Статус устройства - вкл/выкл
	Status bool `json:"status,omitempty"`
}
