/*
 * Телеметрия
 *
 * Описание синхронного API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TelemetryRecord struct {

	Device string `json:"device,omitempty"`

	Serial string `json:"serial,omitempty"`

	Data []TelemetryValue `json:"data,omitempty"`
}
