/*
 * Телеметрия
 *
 * Описание синхронного API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Results []TelemetryRecord `json:"results,omitempty"`
	Page    float64           `json:"page,omitempty"`
	PerPage float64           `json:"per_page,omitempty"`
	Total   float64           `json:"total,omitempty"`
}
