global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090

  - job_name: telemetry
    scheme: http
    static_configs:
      - targets:
        - telemetry:8080

  - job_name: devices
    scheme: http
    static_configs:
      - targets:
        - devices:8080