/*
 * Телеметрия
 *
 * Описание синхронного API
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"devices/controller"
	"devices/repository"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/spf13/viper"
)

const (
	CFG_PORT                  = "PORT"
	CFG_PORT_DEFAULT          = "8080"
	CFG_KAFKA_ADDRESS         = "KAFKA"
	CFG_KAFKA_ADDRESS_DEFAULT = "kafka:9092"
)

func prometheusHandler() gin.HandlerFunc {
	h := promhttp.Handler()

	return func(c *gin.Context) {
		h.ServeHTTP(c.Writer, c.Request)
	}
}

func main() {
	// Prepare config
	viper.AutomaticEnv()
	viper.SetDefault(CFG_PORT, CFG_PORT_DEFAULT)
	viper.SetDefault(CFG_KAFKA_ADDRESS, CFG_KAFKA_ADDRESS_DEFAULT)

	// Prepare API
	r := gin.Default()

	repo := repository.NewMemoryRepository()
	cnt := controller.NewController(repo)

	// Start HTTP
	r.GET("/", cnt.Index())
	r.POST("/device", cnt.AddDevice())
	r.GET("/device/:id", cnt.GetDevice())
	r.POST("/command/:id", cnt.CallCommand())
	r.GET("/metrics", prometheusHandler())

	r.Run(":" + viper.GetString(CFG_PORT))
}
